# example config file for authentication MultiInfo HTTPS API
login: luka
password: test
service_id: 1

# Optionally you can specify full path to certificate files
client_cert: /home/luka/weblify.cert
client_key: /home/luka/weblify.key